/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author faiz_
 */
public class DataTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form DataTransaksi
     */
    public DataTransaksi() {
        initComponents();
        mySettings();
    }

    public void mySettings(){
       panelTabelNota.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        textFieldNoNota = new javax.swing.JTextField();
        labelJudul = new javax.swing.JLabel();
        labelNoNota = new javax.swing.JLabel();
        labelKodeBarang = new javax.swing.JLabel();
        labelUkuran = new javax.swing.JLabel();
        labelMetodePembayaran = new javax.swing.JLabel();
        buttonTambahKeNota = new javax.swing.JButton();
        labelJumlah = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        ComboBoxUkuran = new javax.swing.JComboBox<>();
        comboBoxMetodePembelian = new javax.swing.JComboBox<>();
        sliderJumlahBarang = new javax.swing.JSlider();
        labelTotalHarga = new javax.swing.JLabel();
        labelTotalHargaKeseluruhan = new javax.swing.JLabel();
        buttonTambahKeDataTransaksi = new javax.swing.JButton();
        buttonCariNota = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelTabelNota = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNota = new javax.swing.JTable();
        labelJudulNota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 240, 251));

        textFieldNoNota.setText("No Nota");
        textFieldNoNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoNotaActionPerformed(evt);
            }
        });

        labelJudul.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelJudul.setText("Pendataan Transaksi");

        labelNoNota.setText("No Nota");

        labelKodeBarang.setText("Kode Barang");

        labelUkuran.setText("Ukuran");

        labelMetodePembayaran.setText("Metode Pembelian");

        buttonTambahKeNota.setBackground(new java.awt.Color(128, 117, 255));
        buttonTambahKeNota.setText("Tambah ke nota");
        buttonTambahKeNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahKeNotaActionPerformed(evt);
            }
        });

        labelJumlah.setText("Jumlah");

        jTextField2.setText("Kode Barang");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        ComboBoxUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL", "XXXL" }));
        ComboBoxUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxUkuranActionPerformed(evt);
            }
        });

        comboBoxMetodePembelian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offline", "Shopee", "Tokopedia" }));
        comboBoxMetodePembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMetodePembelianActionPerformed(evt);
            }
        });

        labelTotalHarga.setText("Total Harga");

        labelTotalHargaKeseluruhan.setText("Total Harga Keseluruhan");

        buttonTambahKeDataTransaksi.setBackground(new java.awt.Color(128, 117, 255));
        buttonTambahKeDataTransaksi.setText("Tambah ke Data Transaksi");
        buttonTambahKeDataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahKeDataTransaksiActionPerformed(evt);
            }
        });

        buttonCariNota.setBackground(new java.awt.Color(128, 117, 255));
        buttonCariNota.setText("Cari transaksi");
        buttonCariNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariNotaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(128, 117, 255));

        panelTabelNota.setBackground(new java.awt.Color(128, 117, 255));

        tabelNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Barang", "Ukuran", "Metode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelNota.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                none(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNota);

        labelJudulNota.setForeground(new java.awt.Color(255, 255, 255));
        labelJudulNota.setText("Tabel Nota");

        javax.swing.GroupLayout panelTabelNotaLayout = new javax.swing.GroupLayout(panelTabelNota);
        panelTabelNota.setLayout(panelTabelNotaLayout);
        panelTabelNotaLayout.setHorizontalGroup(
            panelTabelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(panelTabelNotaLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(labelJudulNota)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        panelTabelNotaLayout.setVerticalGroup(
            panelTabelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelNotaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelJudulNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabelNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelTabelNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotalHargaKeseluruhan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalHarga)
                            .addComponent(labelMetodePembayaran)
                            .addComponent(labelJumlah)
                            .addComponent(labelKodeBarang)
                            .addComponent(labelUkuran)
                            .addComponent(labelNoNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(comboBoxMetodePembelian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(ComboBoxUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(buttonCariNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(sliderJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTambahKeNota)
                            .addComponent(buttonTambahKeDataTransaksi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeBarang)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUkuran)
                    .addComponent(ComboBoxUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetodePembayaran)
                    .addComponent(comboBoxMetodePembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlah)
                    .addComponent(sliderJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalHarga)
                    .addComponent(buttonTambahKeNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalHargaKeseluruhan)
                    .addComponent(buttonTambahKeDataTransaksi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNoNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoNotaActionPerformed

    private void buttonTambahKeNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahKeNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTambahKeNotaActionPerformed

    private void ComboBoxUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxUkuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxUkuranActionPerformed

    private void comboBoxMetodePembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMetodePembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMetodePembelianActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void buttonTambahKeDataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahKeDataTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTambahKeDataTransaksiActionPerformed

    private void none(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void buttonCariNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariNotaActionPerformed
        panelTabelNota.setVisible(true);
    }//GEN-LAST:event_buttonCariNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxUkuran;
    private javax.swing.JButton buttonCariNota;
    private javax.swing.JButton buttonTambahKeDataTransaksi;
    private javax.swing.JButton buttonTambahKeNota;
    private javax.swing.JComboBox<String> comboBoxMetodePembelian;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJudulNota;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKodeBarang;
    private javax.swing.JLabel labelMetodePembayaran;
    private javax.swing.JLabel labelNoNota;
    private javax.swing.JLabel labelTotalHarga;
    private javax.swing.JLabel labelTotalHargaKeseluruhan;
    private javax.swing.JLabel labelUkuran;
    private javax.swing.JPanel panelTabelNota;
    private javax.swing.JSlider sliderJumlahBarang;
    private javax.swing.JTable tabelNota;
    private javax.swing.JTextField textFieldNoNota;
    // End of variables declaration//GEN-END:variables
}
