/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Bagas
 */
public class Form_Barang extends javax.swing.JPanel {

    /**
     * Creates new form Form_Barang
     */
    public Form_Barang() {
        initComponents();

        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDataBarang = new javax.swing.JTable();
        tambahBarang_button = new javax.swing.JButton();
        inputCariBarang = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        button_search = new javax.swing.JLabel();
        TambahBarang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        simpan_button = new javax.swing.JButton();
        batal_button_simpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inputKodeBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputNamaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputJumlahBarang = new javax.swing.JTextField();
        ukuran_comboBox = new javax.swing.JComboBox<>();
        simpan_button1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 14, 69));
        jLabel1.setText("DATA BARANG");

        tableDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Ukuran", "Harga Barang", "Stok Barang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDataBarang);

        tambahBarang_button.setBackground(new java.awt.Color(13, 14, 69));
        tambahBarang_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        tambahBarang_button.setForeground(new java.awt.Color(255, 255, 255));
        tambahBarang_button.setText("TAMBAH / UPDATE");
        tambahBarang_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarang_buttonActionPerformed(evt);
            }
        });

        inputCariBarang.setText("Cari ID Barang");
        inputCariBarang.setBorder(null);

        button_search.setIcon(new javax.swing.ImageIcon("C:\\Penyimpanan Utama\\Downloads\\search (1).png")); // NOI18N

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
                            .addGroup(dataBarangLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(tambahBarang_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCariBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_search)
                        .addGap(29, 29, 29))))
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tambahBarang_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataBarang, "card2");

        TambahBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 14, 69));
        jLabel2.setText("DATA BARANG");

        simpan_button.setBackground(new java.awt.Color(13, 14, 69));
        simpan_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        simpan_button.setForeground(new java.awt.Color(255, 255, 255));
        simpan_button.setText("SIMPAN");
        simpan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_buttonActionPerformed(evt);
            }
        });

        batal_button_simpan.setBackground(new java.awt.Color(13, 14, 69));
        batal_button_simpan.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        batal_button_simpan.setForeground(new java.awt.Color(255, 255, 255));
        batal_button_simpan.setText("BATAL");
        batal_button_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_button_simpanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel3.setText("Kode Barang");

        inputKodeBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputKodeBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel4.setText("Nama Barang");

        inputNamaBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputNamaBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel5.setText("Ukuran");

        jLabel6.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel6.setText("Jumlah Barang");

        inputJumlahBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputJumlahBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ukuran_comboBox.setBackground(new java.awt.Color(245, 245, 245));
        ukuran_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XXL", "XL", "L", "M", "S" }));
        ukuran_comboBox.setBorder(null);

        simpan_button1.setBackground(new java.awt.Color(13, 14, 69));
        simpan_button1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        simpan_button1.setForeground(new java.awt.Color(255, 255, 255));
        simpan_button1.setText("UPDATE");
        simpan_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahBarangLayout = new javax.swing.GroupLayout(TambahBarang);
        TambahBarang.setLayout(TambahBarangLayout);
        TambahBarangLayout.setHorizontalGroup(
            TambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahBarangLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(TambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TambahBarangLayout.createSequentialGroup()
                        .addGroup(TambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(TambahBarangLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))
                    .addGroup(TambahBarangLayout.createSequentialGroup()
                        .addComponent(simpan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpan_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batal_button_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TambahBarangLayout.createSequentialGroup()
                        .addGroup(TambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(inputKodeBarang)
                            .addComponent(inputNamaBarang)
                            .addComponent(ukuran_comboBox, 0, 1223, Short.MAX_VALUE)
                            .addComponent(inputJumlahBarang))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        TambahBarangLayout.setVerticalGroup(
            TambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahBarangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batal_button_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ukuran_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        mainPanel.add(TambahBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBarang_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarang_buttonActionPerformed
       mainPanel.removeAll();
       mainPanel.repaint();
       mainPanel.revalidate();
       
       mainPanel.add(TambahBarang);
       mainPanel.repaint();
       mainPanel.revalidate();
    }//GEN-LAST:event_tambahBarang_buttonActionPerformed

    private void simpan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_buttonActionPerformed
        // Kode buat simpan barang baru ke database stok barang
    }//GEN-LAST:event_simpan_buttonActionPerformed

    private void batal_button_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_button_simpanActionPerformed
        // TODO add your handling code here:
       mainPanel.removeAll();
       mainPanel.repaint();
       mainPanel.revalidate();
       
       mainPanel.add(dataBarang);
       mainPanel.repaint();
       mainPanel.revalidate();
    }//GEN-LAST:event_batal_button_simpanActionPerformed

    private void simpan_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_button1ActionPerformed
        // Kode buat update data barang ke database stok barang
    }//GEN-LAST:event_simpan_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TambahBarang;
    private javax.swing.JButton batal_button_simpan;
    private javax.swing.JLabel button_search;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JTextField inputCariBarang;
    private javax.swing.JTextField inputJumlahBarang;
    private javax.swing.JTextField inputKodeBarang;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton simpan_button;
    private javax.swing.JButton simpan_button1;
    private javax.swing.JTable tableDataBarang;
    private javax.swing.JButton tambahBarang_button;
    private javax.swing.JComboBox<String> ukuran_comboBox;
    // End of variables declaration//GEN-END:variables
}
