package Main;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Bagas
 */
public class Form_Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Form_Transaksi
     */
    public Form_Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        riwayatTransaksi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDataTransaksi = new javax.swing.JTable();
        TransaksiBaru_button = new javax.swing.JButton();
        button_search = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        inputCariTransaksi = new javax.swing.JTextField();
        transaksiBaru = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        tambahTransaksi_button = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        inputJumlahBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ukuran_comboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inputNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputKodeBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ukuran_comboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updateNota_button = new javax.swing.JButton();
        batal_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        riwayatTransaksi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 14, 69));
        jLabel2.setText("RIWAYAT TRANSAKSI");

        tableDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No Nota", "Kode Barang", "Ukuran", "Jumlah ", "Total Harga", "Tanggal Transaksi", "Metode Pembelian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDataTransaksi);

        TransaksiBaru_button.setBackground(new java.awt.Color(13, 14, 69));
        TransaksiBaru_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        TransaksiBaru_button.setForeground(new java.awt.Color(255, 255, 255));
        TransaksiBaru_button.setText("TRANSAKSI BARU");
        TransaksiBaru_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiBaru_buttonActionPerformed(evt);
            }
        });

        button_search.setIcon(new javax.swing.ImageIcon("C:\\Penyimpanan Utama\\Downloads\\search (1).png")); // NOI18N

        inputCariTransaksi.setText("Cari No Nota");
        inputCariTransaksi.setBorder(null);

        javax.swing.GroupLayout riwayatTransaksiLayout = new javax.swing.GroupLayout(riwayatTransaksi);
        riwayatTransaksi.setLayout(riwayatTransaksiLayout);
        riwayatTransaksiLayout.setHorizontalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TransaksiBaru_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(1064, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riwayatTransaksiLayout.createSequentialGroup()
                        .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                                .addGap(0, 1060, Short.MAX_VALUE)
                                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_search)))
                        .addGap(36, 36, 36))))
        );
        riwayatTransaksiLayout.setVerticalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransaksiBaru_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
        );

        mainPanel.add(riwayatTransaksi, "card2");

        transaksiBaru.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 14, 69));
        jLabel3.setText("RIWAYAT TRANSAKSI");

        tambahTransaksi_button.setBackground(new java.awt.Color(13, 14, 69));
        tambahTransaksi_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        tambahTransaksi_button.setForeground(new java.awt.Color(255, 255, 255));
        tambahTransaksi_button.setText("TAMBAH TRANSAKSI");
        tambahTransaksi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTransaksi_buttonActionPerformed(evt);
            }
        });

        inputJumlahBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputJumlahBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel6.setText("Jumlah Barang");

        ukuran_comboBox.setBackground(new java.awt.Color(245, 245, 245));
        ukuran_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XXL", "XL", "L", "M", "S" }));
        ukuran_comboBox.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel5.setText("Ukuran");

        inputNamaBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputNamaBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel4.setText("Kode Barang");

        inputKodeBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputKodeBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel7.setText("No Nota");

        ukuran_comboBox2.setBackground(new java.awt.Color(245, 245, 245));
        ukuran_comboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offline", "Shopee", "Tokopedia" }));
        ukuran_comboBox2.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel9.setText("Metode Pembayaran");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Ukuran", "Jumlah", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        updateNota_button.setBackground(new java.awt.Color(13, 14, 69));
        updateNota_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        updateNota_button.setForeground(new java.awt.Color(255, 255, 255));
        updateNota_button.setText("UPDATE NOTA");
        updateNota_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNota_buttonActionPerformed(evt);
            }
        });

        batal_button.setBackground(new java.awt.Color(13, 14, 69));
        batal_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        batal_button.setForeground(new java.awt.Color(255, 255, 255));
        batal_button.setText("BATAL");
        batal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_buttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel8.setText("Nota");

        javax.swing.GroupLayout transaksiBaruLayout = new javax.swing.GroupLayout(transaksiBaru);
        transaksiBaru.setLayout(transaksiBaruLayout);
        transaksiBaruLayout.setHorizontalGroup(
            transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiBaruLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(transaksiBaruLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiBaruLayout.createSequentialGroup()
                        .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(transaksiBaruLayout.createSequentialGroup()
                                .addComponent(tambahTransaksi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateNota_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(batal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transaksiBaruLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(738, 738, 738)
                                .addComponent(jLabel8)))
                        .addContainerGap(325, Short.MAX_VALUE))
                    .addGroup(transaksiBaruLayout.createSequentialGroup()
                        .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputJumlahBarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ukuran_comboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNamaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputKodeBarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ukuran_comboBox2, 0, 762, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        transaksiBaruLayout.setVerticalGroup(
            transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiBaruLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahTransaksi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateNota_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(transaksiBaruLayout.createSequentialGroup()
                        .addComponent(inputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ukuran_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ukuran_comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(transaksiBaru, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TransaksiBaru_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiBaru_buttonActionPerformed
       mainPanel.removeAll();
       mainPanel.repaint();
       mainPanel.revalidate();
       
       mainPanel.add(transaksiBaru);
       mainPanel.repaint();
       mainPanel.revalidate();
    }//GEN-LAST:event_TransaksiBaru_buttonActionPerformed

    private void tambahTransaksi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTransaksi_buttonActionPerformed
        // Button buat tambah transaski ke dalam riwayat
    }//GEN-LAST:event_tambahTransaksi_buttonActionPerformed

    private void updateNota_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNota_buttonActionPerformed
        // button buat update nota, supaya bisa liat harga total sementara
    }//GEN-LAST:event_updateNota_buttonActionPerformed

    private void batal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_buttonActionPerformed
       mainPanel.removeAll();
       mainPanel.repaint();
       mainPanel.revalidate();
       
       mainPanel.add(riwayatTransaksi);
       mainPanel.repaint();
       mainPanel.revalidate();
    }//GEN-LAST:event_batal_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransaksiBaru_button;
    private javax.swing.JButton batal_button;
    private javax.swing.JLabel button_search;
    private javax.swing.JTextField inputCariTransaksi;
    private javax.swing.JTextField inputJumlahBarang;
    private javax.swing.JTextField inputKodeBarang;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel riwayatTransaksi;
    private javax.swing.JTable tableDataTransaksi;
    private javax.swing.JButton tambahTransaksi_button;
    private javax.swing.JPanel transaksiBaru;
    private javax.swing.JComboBox<String> ukuran_comboBox;
    private javax.swing.JComboBox<String> ukuran_comboBox2;
    private javax.swing.JButton updateNota_button;
    // End of variables declaration//GEN-END:variables
}
