package Main;

import java.awt.Color;
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Bagas
 */
public class Form_Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Form_Transaksi
     */
    public Form_Transaksi(String os) {
        initComponents(os);
        
        tableDataTransaksi.getTableHeader().setFont(new Font("Lato", Font.PLAIN, 12));
        tableDataTransaksi.getTableHeader().setOpaque(false);
        tableDataTransaksi.getTableHeader().setForeground(new Color(0,0,0));
        tableDataTransaksi.setRowHeight(25);  
    }
    
        
    void cleanTextField() {
        txt_NoNota.setText("Input Keyword");
     
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String os) {

        mainPanel = new javax.swing.JPanel();
        riwayatTransaksi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDataTransaksi = new javax.swing.JTable();
        TransaksiBaru_button = new javax.swing.JButton();
        button_search = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_NoNota = new javax.swing.JTextField();
        asc_nota = new javax.swing.JButton();
        desc_Kodebarang = new javax.swing.JButton();
        desc_KodeBarang = new javax.swing.JButton();
        asc_kodebarang1 = new javax.swing.JButton();
        desc_ukuran = new javax.swing.JButton();
        asc_ukuran = new javax.swing.JButton();
        desc_jumlah = new javax.swing.JButton();
        asc_jumlah = new javax.swing.JButton();
        desc_totalBarang = new javax.swing.JButton();
        asc_totalHarga = new javax.swing.JButton();
        desc_TanggalTransaksi = new javax.swing.JButton();
        asc_tanggalTransaksi = new javax.swing.JButton();
        asc_MetodePembelian = new javax.swing.JButton();
        desc_MetodePembelian = new javax.swing.JButton();
        transaksiBaru = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        tambahTransaksi_button = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        inputJumlahBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ukuran_comboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inputNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputKodeBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ukuran_comboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        HitungTotal_button = new javax.swing.JButton();
        batal_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        batal_button1 = new javax.swing.JButton();
        TOTALHARGA = new javax.swing.JTextField();
        hapusBarangNota_button2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        riwayatTransaksi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 14, 69));
        jLabel2.setText("RIWAYAT TRANSAKSI");

        tableDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No Nota", "Kode Barang", "Ukuran", "Jumlah ", "Total Harga", "Tanggal Transaksi", "Metode Pembelian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDataTransaksi.setFocusable(false);
        tableDataTransaksi.setGridColor(new java.awt.Color(0, 0, 0));
        tableDataTransaksi.setRowHeight(25);
        tableDataTransaksi.setSelectionBackground(new java.awt.Color(128, 128, 128));
        tableDataTransaksi.setShowGrid(false);
        jScrollPane2.setViewportView(tableDataTransaksi);

        TransaksiBaru_button.setBackground(new java.awt.Color(13, 14, 69));
        TransaksiBaru_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        TransaksiBaru_button.setForeground(new java.awt.Color(255, 255, 255));
        TransaksiBaru_button.setText("TRANSAKSI BARU");
        TransaksiBaru_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiBaru_buttonActionPerformed(evt);
            }
        });

        button_search.setIcon(new javax.swing.ImageIcon("C:\\Penyimpanan Utama\\Downloads\\search (1).png")); // NOI18N

        txt_NoNota.setText("Input Keyword");
        txt_NoNota.setBorder(null);
        txt_NoNota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NoNotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NoNotaFocusLost(evt);
            }
        });

        asc_nota.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\up-arrow (1).png")); // NOI18N
        asc_nota.setBorder(null);
        asc_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asc_notaMousePressed(evt);
            }
        });
        asc_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asc_notaActionPerformed(evt);
            }
        });

        desc_Kodebarang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\down-arrow.png")); // NOI18N
        desc_Kodebarang.setBorder(null);
        desc_Kodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_KodebarangActionPerformed(evt);
            }
        });

        desc_KodeBarang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\down-arrow.png")); // NOI18N
        desc_KodeBarang.setBorder(null);
        desc_KodeBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desc_KodeBarangMousePressed(evt);
            }
        });
        desc_KodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_KodeBarangActionPerformed(evt);
            }
        });

        asc_kodebarang1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\up-arrow (1).png")); // NOI18N
        asc_kodebarang1.setBorder(null);
        asc_kodebarang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asc_kodebarang1MousePressed(evt);
            }
        });
        asc_kodebarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asc_kodebarang1ActionPerformed(evt);
            }
        });

        desc_ukuran.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\down-arrow.png")); // NOI18N
        desc_ukuran.setBorder(null);
        desc_ukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desc_ukuranMousePressed(evt);
            }
        });
        desc_ukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_ukuranActionPerformed(evt);
            }
        });

        asc_ukuran.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\up-arrow (1).png")); // NOI18N
        asc_ukuran.setBorder(null);
        asc_ukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asc_ukuranMousePressed(evt);
            }
        });
        asc_ukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asc_ukuranActionPerformed(evt);
            }
        });

        desc_jumlah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\down-arrow.png")); // NOI18N
        desc_jumlah.setBorder(null);
        desc_jumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desc_jumlahMousePressed(evt);
            }
        });
        desc_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_jumlahActionPerformed(evt);
            }
        });

        asc_jumlah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\up-arrow (1).png")); // NOI18N
        asc_jumlah.setBorder(null);
        asc_jumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asc_jumlahMousePressed(evt);
            }
        });
        asc_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asc_jumlahActionPerformed(evt);
            }
        });

        desc_totalBarang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\down-arrow.png")); // NOI18N
        desc_totalBarang.setBorder(null);
        desc_totalBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desc_totalBarangMousePressed(evt);
            }
        });
        desc_totalBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_totalBarangActionPerformed(evt);
            }
        });

        asc_totalHarga.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\up-arrow (1).png")); // NOI18N
        asc_totalHarga.setBorder(null);
        asc_totalHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asc_totalHargaMousePressed(evt);
            }
        });
        asc_totalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asc_totalHargaActionPerformed(evt);
            }
        });

        desc_TanggalTransaksi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\down-arrow.png")); // NOI18N
        desc_TanggalTransaksi.setBorder(null);
        desc_TanggalTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desc_TanggalTransaksiMousePressed(evt);
            }
        });
        desc_TanggalTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_TanggalTransaksiActionPerformed(evt);
            }
        });

        asc_tanggalTransaksi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\up-arrow (1).png")); // NOI18N
        asc_tanggalTransaksi.setBorder(null);
        asc_tanggalTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asc_tanggalTransaksiMousePressed(evt);
            }
        });
        asc_tanggalTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asc_tanggalTransaksiActionPerformed(evt);
            }
        });

        asc_MetodePembelian.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\up-arrow (1).png")); // NOI18N
        asc_MetodePembelian.setBorder(null);
        asc_MetodePembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asc_MetodePembelianMousePressed(evt);
            }
        });
        asc_MetodePembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asc_MetodePembelianActionPerformed(evt);
            }
        });

        desc_MetodePembelian.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bagas\\OneDrive\\Documents\\NetBeansProjects\\UBMERCH\\src\\main\\java\\image_main\\down-arrow.png")); // NOI18N
        desc_MetodePembelian.setBorder(null);
        desc_MetodePembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desc_MetodePembelianMousePressed(evt);
            }
        });
        desc_MetodePembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_MetodePembelianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout riwayatTransaksiLayout = new javax.swing.GroupLayout(riwayatTransaksi);
        riwayatTransaksi.setLayout(riwayatTransaksiLayout);
        riwayatTransaksiLayout.setHorizontalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TransaksiBaru_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(1270, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riwayatTransaksiLayout.createSequentialGroup()
                        .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txt_NoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(asc_nota)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(desc_Kodebarang)
                                        .addGap(173, 173, 173)
                                        .addComponent(asc_kodebarang1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(desc_KodeBarang)
                                        .addGap(164, 164, 164)
                                        .addComponent(asc_ukuran)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(desc_ukuran)
                                        .addGap(168, 168, 168)
                                        .addComponent(asc_jumlah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(desc_jumlah)
                                        .addGap(167, 167, 167)
                                        .addComponent(asc_totalHarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(desc_totalBarang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(asc_tanggalTransaksi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                                                .addComponent(desc_TanggalTransaksi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(asc_MetodePembelian)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(desc_MetodePembelian)
                                                .addGap(48, 48, 48)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_search)))
                        .addGap(36, 36, 36))))
        );
        riwayatTransaksiLayout.setVerticalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_NoNota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransaksiBaru_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc_TanggalTransaksi)
                            .addComponent(asc_tanggalTransaksi)
                            .addComponent(desc_MetodePembelian)
                            .addComponent(asc_MetodePembelian)
                            .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(asc_totalHarga)
                                .addComponent(desc_totalBarang)
                                .addComponent(asc_jumlah)
                                .addComponent(desc_jumlah)
                                .addComponent(asc_ukuran)
                                .addComponent(desc_ukuran)
                                .addComponent(asc_kodebarang1)
                                .addComponent(desc_KodeBarang))))
                    .addComponent(asc_nota)
                    .addComponent(desc_Kodebarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        mainPanel.add(riwayatTransaksi, "card2");

        transaksiBaru.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 14, 69));
        jLabel3.setText("RIWAYAT TRANSAKSI");

        tambahTransaksi_button.setBackground(new java.awt.Color(13, 14, 69));
        tambahTransaksi_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        tambahTransaksi_button.setForeground(new java.awt.Color(255, 255, 255));
        tambahTransaksi_button.setText("TAMBAH TRANSAKSI");
        tambahTransaksi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTransaksi_buttonActionPerformed(evt);
            }
        });

        inputJumlahBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputJumlahBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel6.setText("Jumlah Barang");

        ukuran_comboBox.setBackground(new java.awt.Color(245, 245, 245));
        ukuran_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XXL", "XL", "L", "M", "S" }));
        ukuran_comboBox.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel5.setText("Ukuran");

        inputNamaBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputNamaBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel4.setText("Kode Barang");

        inputKodeBarang.setBackground(new java.awt.Color(245, 245, 245));
        inputKodeBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel7.setText("No Nota");

        ukuran_comboBox2.setBackground(new java.awt.Color(245, 245, 245));
        ukuran_comboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offline", "Shopee", "Tokopedia" }));
        ukuran_comboBox2.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel9.setText("Metode Pembayaran");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Ukuran", "Jumlah", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        HitungTotal_button.setBackground(new java.awt.Color(13, 14, 69));
        HitungTotal_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        HitungTotal_button.setForeground(new java.awt.Color(255, 255, 255));
        HitungTotal_button.setText("HITUNG TOTAL");
        HitungTotal_button.setToolTipText("");
        HitungTotal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungTotal_buttonActionPerformed(evt);
            }
        });

        batal_button.setBackground(new java.awt.Color(13, 14, 69));
        batal_button.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        batal_button.setForeground(new java.awt.Color(255, 255, 255));
        batal_button.setText("BATAL");
        batal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_buttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel8.setText("Nota");

        batal_button1.setBackground(new java.awt.Color(13, 14, 69));
        batal_button1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        batal_button1.setForeground(new java.awt.Color(255, 255, 255));
        batal_button1.setText("TAMBAH BARANG");
        batal_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_button1ActionPerformed(evt);
            }
        });

        TOTALHARGA.setToolTipText("");

        hapusBarangNota_button2.setBackground(new java.awt.Color(13, 14, 69));
        hapusBarangNota_button2.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        hapusBarangNota_button2.setForeground(new java.awt.Color(255, 255, 255));
        hapusBarangNota_button2.setText("HAPUS BARANG");
        hapusBarangNota_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBarangNota_button2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel1.setText("Total Yang Harus Dibayar");

        javax.swing.GroupLayout transaksiBaruLayout = new javax.swing.GroupLayout(transaksiBaru);
        transaksiBaru.setLayout(transaksiBaruLayout);
        transaksiBaruLayout.setHorizontalGroup(
            transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiBaruLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiBaruLayout.createSequentialGroup()
                        .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(transaksiBaruLayout.createSequentialGroup()
                                .addComponent(tambahTransaksi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(batal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transaksiBaruLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(828, 828, 828)
                                .addComponent(jLabel8)))
                        .addContainerGap(265, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiBaruLayout.createSequentialGroup()
                        .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiBaruLayout.createSequentialGroup()
                                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputJumlahBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ukuran_comboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputNamaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputKodeBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ukuran_comboBox2, 0, 762, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(transaksiBaruLayout.createSequentialGroup()
                                        .addComponent(batal_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(hapusBarangNota_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(HitungTotal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiBaruLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TOTALHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(174, 174, 174))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiBaruLayout.createSequentialGroup()
                .addContainerGap(1233, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        transaksiBaruLayout.setVerticalGroup(
            transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiBaruLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahTransaksi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(transaksiBaruLayout.createSequentialGroup()
                        .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transaksiBaruLayout.createSequentialGroup()
                                .addComponent(inputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ukuran_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ukuran_comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batal_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusBarangNota_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HitungTotal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(transaksiBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TOTALHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(transaksiBaru, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tambahTransaksi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTransaksi_buttonActionPerformed
        // Button buat tambah transaski ke dalam riwayat
    }//GEN-LAST:event_tambahTransaksi_buttonActionPerformed

    private void HitungTotal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungTotal_buttonActionPerformed
        // button buat update nota, supaya bisa liat harga total sementara
    }//GEN-LAST:event_HitungTotal_buttonActionPerformed

    private void batal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_buttonActionPerformed
       mainPanel.removeAll();
       mainPanel.repaint();
       mainPanel.revalidate();
       
       mainPanel.add(riwayatTransaksi);
       mainPanel.repaint();
       mainPanel.revalidate();
    }//GEN-LAST:event_batal_buttonActionPerformed

    private void batal_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batal_button1ActionPerformed

    private void hapusBarangNota_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBarangNota_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusBarangNota_button2ActionPerformed

    private void txt_NoNotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NoNotaFocusLost
        // TODO add your handling code here:
        String NoNota = txt_NoNota.getText();
        if(NoNota.equals("")||NoNota.equals("Password")) {
            txt_NoNota.setText("Password");
        }
    }//GEN-LAST:event_txt_NoNotaFocusLost

    private void txt_NoNotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NoNotaFocusGained
        // TODO add your handling code here:
        String NoNota = txt_NoNota.getText();
        if(NoNota.equals("Input Keyword")) {
            txt_NoNota.setText("");
        }
    }//GEN-LAST:event_txt_NoNotaFocusGained

    private void TransaksiBaru_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiBaru_buttonActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(transaksiBaru);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_TransaksiBaru_buttonActionPerformed

    private void asc_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asc_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_notaActionPerformed

    private void desc_KodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_KodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_KodebarangActionPerformed

    private void desc_KodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_KodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_KodeBarangActionPerformed

    private void asc_kodebarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asc_kodebarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_kodebarang1ActionPerformed

    private void desc_ukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_ukuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_ukuranActionPerformed

    private void asc_ukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asc_ukuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_ukuranActionPerformed

    private void desc_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_jumlahActionPerformed

    private void asc_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asc_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_jumlahActionPerformed

    private void desc_totalBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_totalBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_totalBarangActionPerformed

    private void asc_totalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asc_totalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_totalHargaActionPerformed

    private void desc_TanggalTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_TanggalTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_TanggalTransaksiActionPerformed

    private void asc_tanggalTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asc_tanggalTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_tanggalTransaksiActionPerformed

    private void asc_MetodePembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asc_MetodePembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_MetodePembelianActionPerformed

    private void desc_MetodePembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_MetodePembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_MetodePembelianActionPerformed

    private void asc_notaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc_notaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_notaMousePressed

    private void asc_kodebarang1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc_kodebarang1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_kodebarang1MousePressed

    private void desc_KodeBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desc_KodeBarangMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_KodeBarangMousePressed

    private void asc_ukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc_ukuranMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_ukuranMousePressed

    private void desc_ukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desc_ukuranMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_ukuranMousePressed

    private void asc_jumlahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc_jumlahMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_jumlahMousePressed

    private void desc_jumlahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desc_jumlahMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_jumlahMousePressed

    private void asc_totalHargaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc_totalHargaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_totalHargaMousePressed

    private void desc_totalBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desc_totalBarangMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_totalBarangMousePressed

    private void asc_tanggalTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc_tanggalTransaksiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_tanggalTransaksiMousePressed

    private void desc_TanggalTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desc_TanggalTransaksiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_TanggalTransaksiMousePressed

    private void asc_MetodePembelianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc_MetodePembelianMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asc_MetodePembelianMousePressed

    private void desc_MetodePembelianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desc_MetodePembelianMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_MetodePembelianMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HitungTotal_button;
    private javax.swing.JTextField TOTALHARGA;
    private javax.swing.JButton TransaksiBaru_button;
    private javax.swing.JButton asc_MetodePembelian;
    private javax.swing.JButton asc_jumlah;
    private javax.swing.JButton asc_kodebarang1;
    private javax.swing.JButton asc_nota;
    private javax.swing.JButton asc_tanggalTransaksi;
    private javax.swing.JButton asc_totalHarga;
    private javax.swing.JButton asc_ukuran;
    private javax.swing.JButton batal_button;
    private javax.swing.JButton batal_button1;
    private javax.swing.JLabel button_search;
    private javax.swing.JButton desc_KodeBarang;
    private javax.swing.JButton desc_Kodebarang;
    private javax.swing.JButton desc_MetodePembelian;
    private javax.swing.JButton desc_TanggalTransaksi;
    private javax.swing.JButton desc_jumlah;
    private javax.swing.JButton desc_totalBarang;
    private javax.swing.JButton desc_ukuran;
    private javax.swing.JButton hapusBarangNota_button2;
    private javax.swing.JTextField inputJumlahBarang;
    private javax.swing.JTextField inputKodeBarang;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel riwayatTransaksi;
    private javax.swing.JTable tableDataTransaksi;
    private javax.swing.JButton tambahTransaksi_button;
    private javax.swing.JPanel transaksiBaru;
    private javax.swing.JTextField txt_NoNota;
    private javax.swing.JComboBox<String> ukuran_comboBox;
    private javax.swing.JComboBox<String> ukuran_comboBox2;
    // End of variables declaration//GEN-END:variables
}
